### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by simendsjo** [dloureiro/pandoc-gpp#1]
Trying a file like this

```
\include{t.txt}
```

And t.txt as

```
testing
```

when running `pandoc-gpp t.pandoc` gives

```
pandoc-gpp dave3605_notater.pandoc
Traceback (most recent call last):
  File "/usr/bin/pandoc-gpp", line 4, in <module>
    __import__('pkg_resources').run_script('pandoc-gpp==0.2.5', 'pandoc-gpp')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 696, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1621, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pandoc_gpp-0.2.5-py2.7.egg/EGG-INFO/scripts/pandoc-gpp", line 113, in <module>

  File "/usr/lib/python2.7/site-packages/pandoc_gpp-0.2.5-py2.7.egg/EGG-INFO/scripts/pandoc-gpp", line 93, in main

  File "/usr/lib/python2.7/site-packages/pandoc_gpp-0.2.5-py2.7.egg/EGG-INFO/scripts/pandoc-gpp", line 72, in parseOptions

TypeError: argument of type 'NoneType' is not iterable
```

**Comment by simendsjo** [comment]
I tried with python3, but I get another error (after running `python3 setup.py install` again).

```
$ pandoc-gpp                                                                                                                                     [±master ●]
Traceback (most recent call last):
  File "/usr/bin/pandoc-gpp", line 4, in <module>
    __import__('pkg_resources').run_script('pandoc-gpp==0.2.5', 'pandoc-gpp')
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 696, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1620, in run_script
    script_code = compile(script_text, script_filename,'exec')
  File "/usr/lib/python3.4/site-packages/pandoc_gpp-0.2.5-py3.4.egg/EGG-INFO/scripts/pandoc-gpp", line 43
    print "[log] : Path -> " + os.path.dirname(__file__) + "/.."
                           ^
SyntaxError: invalid syntax
```
